[pytest]
filterwarnings =
    ignore:The configuration option "asyncio_default_fixture_loop_scope" is unset:pytest.PytestDeprecationWarning
    ignore:The 'app' shortcut is now deprecated:DeprecationWarning
